JMGG.ManageProject.Web/Controllers/UserManageController.cs
using JMGG.ManageProject.Business;
using JMGG.ManageProject.Common;
using JMGG.ManageProject.Model;
using JMGG.ManageProject.Model.User;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JMGG.ManageProject.Web.Controllers
{
    public class UserManageController : BaseController
    {
        private static readonly UserManageLogic userMangeLogic = new UserManageLogic();

        // GET: UserManage
        public ActionResult Index()
        {
            ViewBag.IsAdmin = true;
            return View("~/Views/UserManage/UserManage.cshtml");
        }

        /// <summary>
        /// 用户列表
        /// </summary>
        /// <returns></returns>
        public JsonResult GetUserManageList()
        {
            try
            {
                int page = !string.IsNullOrEmpty(Request["page"]) ? Convert.ToInt32(Request["page"]) : 1;
                int limit = !string.IsNullOrEmpty(Request["limit"]) ? Convert.ToInt32(Request["limit"]) : 10;
                var businessID = !string.IsNullOrEmpty(Request["UserId"]) ? Request["UserId"] : "";
                var userName = !string.IsNullOrEmpty(Request["UserName"]) ? Request["UserName"] : "";

                var paramRequest = new UseManageRequest
                {
                    UserName = userName,
                    BussinessID = businessID,
                    PageIndex = page,
                    PageSize = limit
                };
                if (paramRequest.PageIndex == 0)
                    paramRequest.PageIndex = 1;
                else
                    paramRequest.PageIndex = (paramRequest.PageIndex / 10) + 1;

                var result = userMangeLogic.QueryUserListPage(paramRequest);
                if (result != null && result.count > 0)
                {
                    result.msg = "SUCCESS";
                    result.code = 0;
                }
                return Json(result);
            }
            catch (Exception ex)
            {
                LogWriter.error($"GetUserManageList=>获取用户信息的异常：{ex.ToString() + ex.Message}");
                return Json(new UseManagePageResponse() { code = 9 });
            }
        }

        /// <summary>
        /// 新增用户
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddUser()
        {
            var param = string.IsNullOrEmpty(Request["param"]) ? "" : Request["param"];
            if (param == "")
                return Json(new BaseResponse { result = false, msg = "请求参数不能为空" });

            var userObj = JsonConvert.DeserializeObject<UseManageEntity>(param);
            userObj.BussinessID = userObj.UserId;
            userObj.CreateTime = DateTime.Now;
            userObj.IsDelete = 0;
            userObj.CreateUser = base.UserInfo != null ? base.UserInfo.UserName : "";
            var userInfo = userMangeLogic.InsertUser(userObj);
            return Json(userInfo);
        }

        /// <summary>
        /// 批量删除
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult BathDeleteUser()
        {
            var param = string.IsNullOrEmpty(Request["ids"]) ? "" : Request["ids"];
            if (param == "")
                return Json(new BaseResponse { result = false, msg = "请求参数不能为空" });

            var userInfo = userMangeLogic.DeleteUser(param.Split(',').Select(p => Convert.ToInt32(p)).ToList());
            return Json(new BaseResponse { result = userInfo, msg = userInfo ? "删除成功" : "删除失败" });
        }
    }
}

JMGG.ManageProject.Web/Views/UserManage/UserManage.cshtml
@{
    ViewBag.Title = "用户管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<blockquote class="layui-elem-quote blog-manage-breadcrumb" style="margin-top: 5px;">
    <span class="layui-breadcrumb">
        <a>广告计划管理</a>
        <a href="@Url.Action("Index", "UserManage")"><cite>广告主列表</cite></a>
    </span>
</blockquote>

<div class="layui-row" style="padding-left: 5px;">
    <div class="demoTable">
        商户ID：
        <div class="layui-inline">
            <input class="layui-input" name="searUserId" id="searUserId" autocomplete="off">
        </div>
        登录账号：
        <div class="layui-inline">
            <input class="layui-input" name="searUserName" id="searUserName" autocomplete="off">
        </div>
        <button class="layui-btn" data-type="reload">搜索</button>
    </div>

    <div class="layui-col-md12">
        <table id="tblUser" lay-filter="tblUser"></table>
    </div>

    <script type="text/html" id="toolbarDemo">
        <div class="layui-btn-container">
            <button class="layui-btn layui-btn-sm" lay-event="getAddUser">新增广告主</button>
            @*<button class="layui-btn layui-btn-sm" lay-event="getCheckData">批量删除</button>*@
        </div>
    </script>

    <script type="text/html" id="barDemo">
        @*<a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>*@
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>

    <!--from表单-->
    <div id="formUser" style="display:none;">
        <form class="layui-form" lay-filter="formuserinfo">
            <input type="hidden" value="" name="Status" id="formStatus" />
            <div class="layui-form-item">
                <label class="layui-form-label">商家ID</label>
                <div class="layui-input-block">
                    <input type="text" name="UserId" lay-verify="userid" placeholder="请输入商户ID" autocomplete="off" class="layui-input" style="width:80%;">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">登录账号</label>
                <div class="layui-input-block">
                    <input type="text" name="UserName" required lay-verify="required" placeholder="请输入用户姓名" autocomplete="off" class="layui-input" style="width:80%;">
                </div>
            </div>

            <div class="layui-form-item">
                <label class="layui-form-label">登录密码</label>
                <div class="layui-input-inline">
                    <input type="password" name="PassWord" required lay-verify="required" placeholder="请输入密码" autocomplete="off" class="layui-input" style="width:80%;">
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">公司名称</label>
                <div class="layui-input-block">
                    <input type="text" name="CompanyName" required lay-verify="required" placeholder="请输入公司名称" autocomplete="off" class="layui-input" style="width:80%;">
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <input class="layui-btn" type="button" lay-submit lay-filter="adduserForm" value="立即提交">
                    <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
            </div>
        </form>
    </div>

</div>

@section Scripts{
    <script type="text/javascript">
        layui.use(['form', 'jquery', 'table', 'layer'], function () {
            var $ = layui.jquery;
            var form = layui.form;
            var table = layui.table;
            var layer = layui.layer;

            //表格加载
            table.render({
                elem: '#tblUser'
                , url: '/UserManage/GetUserManageList' //数据接口
                , page: true //开启分页
                , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
                , defaultToolbar: []
                , title: '用户数据表'
                , limit: 10   //一页能够显示的最大数目
                , limits: [10, 15, 20]
                , method: 'post'  //提交方式
                , cols: [[ //表头
                      { type: 'checkbox', fixed: 'left', hide: true }
                    , { field: 'BussinessID', title: '商家Id', width: 110, sort: true }
                    , { field: 'UserName', title: '登录账号', width: 120, sort: true }
                    , { field: 'CompanyName', title: '公司名称', width: 120, sort: true }
                    , { field: 'CreateTimeStr', title: '创建时间', width: 190, sort: true }
                    , { fixed: 'right', title: '操作', toolbar: '#barDemo', width: 150 }
                ]]
                , id: 'testReload'
            });

            //头工具栏事件
            table.on('toolbar(tblUser)', function (obj) {
                switch (obj.event) {
                    //case 'getCheckData':
                    //    var checkStatus = table.checkStatus(obj.config.id);
                    //    var data = checkStatus.data;
                    //    var ids = "";
                    //    $.each(data, function (i, val) {
                    //        if (ids != "")
                    //            ids += ","
                    //        ids += val.Id;
                    //    });
                    //    if (ids == "") {
                    //        layer.alert("请选择用户!");
                    //        return;
                    //    }
                    //    layer.confirm("是否确认批量删除？", function (cindex) {
                    //        $.post("/UserMange/BathDeleteUser", { ids: ids }, function (msg) {
                    //            if (!msg.result) {
                    //                layer.alert(msg.msg);
                    //                return;
                    //            }
                    //            layer.alert("删除成功", function () {
                    //                window.location.reload();
                    //            });
                    //        });
                    //        layer.close(cindex);
                    //    });
                    //    break;
                    case 'getAddUser':
                        $("#formStatus").val("insert");
                        $("form [name='UserId']").removeAttr("disabled");
                        layer.open({
                            skin: 'demo-class',
                            type: 1,
                            shade: [0.8, '#393D49'],
                            shadeClose: false,
                            maxmin: true,
                            area: ['680px', '440px'],
                            content: $("#formUser").html()
                        });
                        break;
                };
            });

            //行工具事件
            table.on('tool(tblUser)', function (obj) {
                var data = obj.data;
                if (obj.event === 'del') {
                    layer.confirm('是否确认删除?', function (index) {
                        $.post("/UserManage/BathDeleteUser", { ids: data.Id }, function (msg) {
                            if (!msg.result) {
                                layer.alert(msg.msg);
                                return;
                            }
                            layer.alert("删除成功", function () {
                                window.location.reload()
                            });
                        });
                        layer.close(index);
                    });
                } else if (obj.event === 'edit') {
                    //$("#formStatus").val("update");
                    //$("form [name='UserId']").attr("disabled", "disabled");
                    //layer.open({
                    //    skin: 'demo-class',
                    //    type: 1,
                    //    shade: [0.8, '#393D49'],
                    //    shadeClose: false,
                    //    maxmin: true,
                    //    area: ['680px', '440px'],
                    //    content: $("#formUser").html()
                    //});
                    ////form赋值 formuserinfo是lay-filter="对应的值"
                    //form.val("formuserinfo", data);
                }
            });

            //查询事件
            var $ = layui.$, active = {
                reload: function () {
                    var searUserId = $('#searUserId');
                    var searUserName = $('#searUserName');
                    //执行重载
                    table.reload('testReload', {
                        page: {
                            curr: 1 //重新从第 1 页开始
                        }
                        , where: {
                            UserId: searUserId.val(),
                            UserName: searUserName.val()
                        }
                    }, 'data');
                }
            };
            $('.demoTable .layui-btn').on('click', function () {
                var type = $(this).data('type');
                active[type] ? active[type].call(this) : '';
            });

            //form自定义验证规则
            form.verify({
                userid: function (value) {
                    if (value.length < 2) return '用户Id至少2个字符';
                    if (value.length > 30) return '用户Id写得太多啦，不要超过30个字符好吗？';
                },
            });
            //form监听提交
            form.on('submit(adduserForm)', function (data) {
                var pramStr = JSON.stringify(data.field);
                $.ajax({
                    type: "POST",
                    url: "/UserManage/AddUser",
                    data: { param: pramStr },
                    dataType: "JSON",
                    success: function (msg) {
                        if (!msg.result) {
                            layer.alert(msg.msg);
                            return;
                        }
                        layer.alert(msg.msg, function () {
                            window.location.reload();
                        });
                    }
                });
                return false;
            });

            //设置菜单选中样式
            var $item = $('.layui-nav > .layui-nav-item .layui-nav-child').children();
            $.each($item, function (i, val) {
                if ($(this).find("a").text() == "用户管理")
                    $(this).addClass('layui-this');
                else
                    $(this).removeClass('layui-this');
            });
        });
    </script>
}