JMGG.ManageProject.Web/Controllers/CreativeController.cs
using JMGG.ManageProject.Business;
using JMGG.ManageProject.Common;
using JMGG.ManageProject.Model;
using JMGG.ManageProject.Model.Creative;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JMGG.ManageProject.Web.Controllers
{

    public class CreativeController : BaseController
    {
        private static readonly CreativeLogic CreativeLogic = new CreativeLogic();

        // GET: CreativePlan
        public ActionResult Index()
        {
            ViewBag.IsAdmin = false;
            ViewBag.UserLoginName = base.UserInfo.CompanyName + "[ID:" + base.UserInfo.BusinessID + "]";
            return View("~/Views/Creative/Index.cshtml");
        }
        public ActionResult From()
        {
            ViewBag.IsAdmin = false;
            ViewBag.UserLoginName = base.UserInfo.CompanyName + "[ID:" + base.UserInfo.BusinessID + "]";
            return View("~/Views/Creative/From.cshtml");
        }
        /// <summary>
        /// 基础信息
        /// </summary>
        /// <returns></returns>
        public JsonResult GetList()
        {
            try
            {
                int page = !string.IsNullOrEmpty(Request["page"]) ? Convert.ToInt32(Request["page"]) : 1;
                int limit = !string.IsNullOrEmpty(Request["limit"]) ? Convert.ToInt32(Request["limit"]) : 10;

                var Introduce = Request["Introduce"] ?? "";
                var SourceID = Request["SourceID"] ?? "";

                var paramRequest = new CreativeRequest
                {
                    PageIndex = page,
                    PageSize = limit,
                    Introduce = Introduce,
                    SourceID = SourceID,
                    UserManageId = base.UserInfo.UserManageID
                };
                if (paramRequest.PageIndex == 0)
                    paramRequest.PageIndex = 1;
                else
                    paramRequest.PageIndex = (paramRequest.PageIndex / 10) + 1;

                var result = CreativeLogic.QueryUserListPage(paramRequest);
                if (result != null && result.count > 0)
                {
                    result.msg = "SUCCESS";
                    result.code = 0;
                }
                return Json(result);
            }
            catch (Exception ex)
            {
                LogWriter.error($"GetUserManageList=>获取基础信息的异常：{ex.ToString() + ex.Message}");
                return Json(new CreativePageResponse() { code = 9 });
            }
        }
        /// <summary>
        /// 新增广告素材
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Add()
        {
            var Video = "Http://" + Request.Url.Authority.ToString() + Request["Video"] ?? "";
            var desc_content = Request["desc_content"] ?? "";

            if (Video == "")
                return Json(new BaseResponse { result = false, msg = "请求参数不能为空" });

            var creativeEntity = new CreativeEntity
            {
                CreateTime = DateTime.Now.ToString(),
                DataType = "1",
                Introduce = desc_content,
                LastUpdateTime = DateTime.Now.ToString(),
                SourceID = "SMALL_VIDEO_" + new Random(Guid.NewGuid().GetHashCode()).Next(0, 999999999).ToString("d5").PadRight(8, '0'),
                Status = "0",
                VideoUrl = Video,
                UserManageId = base.UserInfo.UserManageID,
                UserName = base.UserInfo.UserName,
                BusinessID = base.UserInfo.BusinessID
            };

            var caResponse = CreativeLogic.Insert(creativeEntity);
            return Json(caResponse);
        }

    }
}

JMGG.ManageProject.Web/Controllers/CreativePlanController.cs
using JMGG.ManageProject.Business;
using JMGG.ManageProject.Common;
using JMGG.ManageProject.Model;
using JMGG.ManageProject.Model.CreativePlan;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace JMGG.ManageProject.Web.Controllers
{

    public class CreativePlanController : BaseController
    {
        private static readonly CreativePlanLogic CreativePlanLogic = new CreativePlanLogic();
        private static readonly AdPlanLogLogic adPlanLog = new AdPlanLogLogic();

        // GET: CreativePlan
        public ActionResult Index()
        {
            ViewBag.IsAdmin = false;
            ViewBag.UserLoginName = base.UserInfo.CompanyName + "[ID:" + base.UserInfo.BusinessID + "]";
            return View("~/Views/CreativePlan/Index.cshtml");
        }
        public ActionResult From()
        {
            ViewBag.IsAdmin = false;
            ViewBag.UserLoginName = base.UserInfo.CompanyName + "[ID:" + base.UserInfo.BusinessID + "]";
            return View("~/Views/CreativePlan/From.cshtml");
        }
        /// <summary>
        /// 广告计划
        /// </summary>
        /// <returns></returns>
        public JsonResult GetList()
        {
            try
            {
                int page = !string.IsNullOrEmpty(Request["page"]) ? Convert.ToInt32(Request["page"]) : 1;
                int limit = !string.IsNullOrEmpty(Request["limit"]) ? Convert.ToInt32(Request["limit"]) : 10;

                var ADName = Request["ADName"] ?? "";
                var BusinessPlanID = Request["BusinessPlanID"] ?? "";
                var startLaunchTime = Request["startLaunchTime"] ?? "";
                var endLaunchTime = Request["endLaunchTime"] ?? "";
                var Status = Request["Status"] ?? "";

                var paramRequest = new CreativePlanRequest
                {
                    PageIndex = page,
                    PageSize = limit,
                    ADName = ADName,
                    BusinessPlanID = BusinessPlanID,
                    endLaunchTime = endLaunchTime,
                    startLaunchTime = startLaunchTime,
                    Status = Status,
                    IsAdmin = false,
                    UserManageId = base.UserInfo.UserManageID
                };
                if (paramRequest.PageIndex == 0)
                    paramRequest.PageIndex = 1;
                else
                    paramRequest.PageIndex = (paramRequest.PageIndex / 10) + 1;

                var result = CreativePlanLogic.QueryUserListPage(paramRequest);
                if (result != null && result.count > 0)
                {
                    result.msg = "SUCCESS";
                    result.code = 0;
                }
                return Json(result);
            }
            catch (Exception ex)
            {
                LogWriter.error($"GetUserManageList=>获取基础信息的异常：{ex.ToString() + ex.Message}");
                return Json(new CreativePlanPageResponse() { code = 9 });
            }
        }

        /// <summary>
        /// 更新广告状态
        /// </summary>
        /// <returns></returns>
        public JsonResult UpdateAdvertPlanStatus()
        {
            var isError = false;
            StringBuilder strLog = new StringBuilder();
            strLog.Append($"UpdateAdvertPlanStatus=>更新广告状态\r\n");
            try
            {
                //调用接口方法使用
                var planId = Request["planId"] ?? "";
                var draft_id = Request["draft_id"] ?? "";
                //本地使用
                var newPlanId = Request["newPlanId"] ?? "";
                var id = Request["id"] ?? "0";
                var operationType = Request["operationType"] ?? "";  //操作类型 1：开 2：关
                strLog.Append($"参数:原计划ID：{planId},draft_id:{draft_id},newPlanId:{newPlanId},id:{id},operationType:{operationType}\r\n");
                if (string.IsNullOrWhiteSpace(planId) || string.IsNullOrWhiteSpace(draft_id))
                {
                    return Json(new { result = false, msg = "暂时无法更新广告状态，请联系管理员操作！" });
                }
                //调用接口方法


                //更新本地数据库状态
                var resUpdate = CreativePlanLogic.UpdateAdPlanBySwitch(new CreativePlanEntity
                {
                    Id = Convert.ToInt32(id),
                    Switch = operationType == "1" ? "1" : "2",
                    Status = operationType == "1" ? "2" : "7"
                });
                strLog.Append($"更新广告状态:{resUpdate}\r\n");

                //查询广告信息
                var planEntity = CreativePlanLogic.QueryCreativePlanById(Convert.ToInt32(id));
                var updateLog = operationType == "1" ? "开启广告计划" : "关闭广告计划";
                //插入日志
                var logRes = adPlanLog.InsertAdPlanLog(new AdPlanyLogEntity
                {
                    UserMangeId = base.UserInfo.UserManageID,
                    UserName = base.UserInfo.UserName,
                    BusinessId = base.UserInfo.BusinessID,
                    BusinessPlanID = planEntity.BusinessPlanID,
                    ADPlanID = planEntity.NewAdPlanID,
                    ADName = planEntity.ADName,
                    BillingMethod = planEntity.BillingMethod,
                    OperationType = "修改",
                    CreateUser = base.UserInfo.UserName,
                    OldJson = $"状态:{(operationType == "1" ? "关" : "开")}",
                    NewJson = $"状态:{(operationType == "1" ? "开" : "关")}"
                });
                strLog.Append($"更新广告状态日志:{logRes}\r\n");

                return Json(new { msg = "", result = false });
            }
            catch (Exception ex)
            {
                isError = true;
                strLog.Append($"异常:{ex.ToString() + ex.StackTrace}");
                return Json(new { msg = "异常，请联系管理员处理", result = false });
            }
            finally
            {
                if (isError)
                    LogWriter.error(strLog.ToString());
                else
                    LogWriter.info(strLog.ToString());
            }
        }
    }
}

JMGG.ManageProject.Web/Views/CreativePlan/Index.cshtml
@{
    ViewBag.Title = "广告计划列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    .layui-table-cell {
        font-size: 14px;
        padding: 0 5px;
        height: auto;
        overflow: visible;
        text-overflow: inherit;
        white-space: normal;
        word-break: break-all;
    }
</style>

<blockquote class="layui-elem-quote blog-manage-breadcrumb" style="margin-top: 5px;">
    <span class="layui-breadcrumb">
        <a>推广</a>
        <a href="@Url.Action("Index", "Creative")"><cite>广告计划列表</cite></a>
    </span>
</blockquote>

<div class="layui-fluid" style="margin-top: 30px;">
    <div class="layui-card">
        <div class="layui-form ">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">广告计划名称</label>
                    <div class="layui-input-inline" style="width: 300px; margin-right: 57px;">
                        <input type="text" name="ADName" class="layui-input" value="">
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">商家计划ID</label>
                    <div class="layui-input-inline">
                        <input type="text" name="BusinessPlanID" class="layui-input" value="">
                    </div>
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">投放时间</label>
                    <div id="put_start_time_box" class="layui-input-inline" style="width: 150px;">
                        <input type="text" class="layui-input datetime" id="startLaunchTime" name="startLaunchTime"
                               placeholder="投放开始时间" readonly value="">
                    </div>
                    <div style="display: inline-block; float: left; margin-right: 10px;">
                        ~
                    </div>
                    <div id="put_end_time_box" class="layui-input-inline" style="width: 150px; margin-right: 30px;">
                        <input type="text" class="layui-input datetime" id="endLaunchTime" name="endLaunchTime"
                               placeholder="投放结束时间" readonly value="">
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">广告计划状态</label>
                    <div class="layui-input-inline">
                        <select name="Status" id="Status">
                            <option value="">全部状态</option>
                            <option value="1">待投放</option>
                            <option value="2">投放中</option>
                            <option value="3">已结束</option>
                            <option value="4">等待审核中</option>
                            <option value="5">未通过审核</option>
                            <option value="6">待提交审核</option>
                            <option value="7">已暂停</option>
                        </select>
                    </div>
                </div>
            </div>
            <div style="padding-bottom: 10px;padding-left:12px;">
                <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="LAY-user-front-search">
                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                    <lable i18n="footer.search">搜索</lable>
                </button>
                <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="LAY-user-front-add">
                    <lable i18n="footer.search">新建广告计划</lable>
                </button>
            </div>
        </div>

        <div class="layui-card-body">
            <table id="LAY-CreativePlan" lay-filter="LAY-CreativePlan"></table>
            <script type="text/html" id="barDemo">
                <a class="layui-btn layui-btn-xs" lay-event="start">开启</a>
                <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="end">关闭</a>
                <a class="layui-btn layui-btn-xs" lay-event="report">查看报表</a>
                <a class="layui-btn layui-btn-xs" lay-event="detial" style="display:none;">查看详情</a>
                <a class="layui-btn layui-btn-xs" lay-event="logs">操作记录</a>
            </script>
        </div>
    </div>
</div>

<script>
    layui.use(['form', 'jquery', 'table', 'layer', 'laydate'], function () {
        var $ = layui.jquery;
        var form = layui.form;
        var table = layui.table;
        var layer = layui.layer;
        var laydate = layui.laydate;
        //新增日期插件
        function dateAdd() {
            lay('.datetime').each(function () {
                laydate.render({
                    elem: this,
                    trigger: 'click',
                    type: 'datetime'
                })
            })
        }
        dateAdd();
        table.set({
            parseData: function (res) {
                return {
                    code: res.status, //解析接口状态
                    msg: res.msg, //解析提示文本
                    count: res.data.total ? res.data.total.total : 0, //解析数据长度
                    data: res.data, //解析数据列表
                }
            },
        })
        //表格加载
        var cols = [[
            { field: 'Id', title: 'Id', hide: true }
            , { field: 'DraftId', title: 'DraftId', hide: true }
            , { field: 'NewAdPlanID', title: '广告计划ID', }
            , { field: 'ADPlanID', title: '广告计划ID', hide: true }
            , { field: 'BusinessPlanID', title: '商家计划ID', }
            , { field: 'ADName', title: '名称', }
            , { field: 'DeliveryPoint', title: '投放点位', }
            , { field: 'BillingMethod', title: '计费方式', }
            , { field: 'NewUnitPrice', title: '单价', }
            , { field: 'NewDayBudget', title: '单日预算', }
            , { field: 'CTRPV', title: 'CTR', }
            , { field: 'CRUUV', title: 'ECPM(CPC)', }
            , { field: 'LaunchSchedule', title: '投放排期', }
            , { field: 'LaunchTime', title: '投放时段', }
            , { field: 'Status', title: '状态', templet: function (d) { if (d.Status == 1) { return '待投放' } if (d.Status == 2) { return '投放中' } if (d.Status == 3) { return '已结束' } if (d.Status == 4) { return '等待审核中' } if (d.Status == 5) { return '未通过审核' } if (d.Status == 6) { return '待提交审核' } if (d.Status == 7) { return '已暂停' } } }
            , { field: 'ApprovalReason', title: '审核原因', }
            , { fixed: 'right', title: '操作', toolbar: '#barDemo', width: 300 }
        ]]
        var tableIns = table.render({
            elem: '#LAY-CreativePlan',
            url: '/CreativePlan/GetList', //数据接口
            cols: cols,
            method: 'post',
            done: function (res) { },
            parseData: function (res) {
                return {
                    code: res.code, //解析接口状态
                    msg: res.msg, //解析提示文本
                    count: res.count ? res.count : 0, //解析数据长度
                    data: res.data, //解析数据列表
                }
            },
            page: true,
            text: {
                none: '暂无相关数据',
            },
            defaultToolbar: [],

        })
        //搜索事件
        form.on('submit(LAY-user-front-search)', function (data) {
            var field = data.field
            //执行重载
            tableIns.reload({
                page: {
                    curr: 1,
                },
                where: field,
            })
        })
        form.on('submit(LAY-user-front-add)', function (data) {
            window.location.href = '../CreativePlan/From';
        })

        //行工具事件
        table.on('tool(LAY-CreativePlan)', function (obj) {
            var data = obj.data;
            if (obj.event === 'logs') {
                //查看操作日志
                layer.open({
                    type: 2,
                    zIndex: 999,
                    title: '操作日志'
                    , skin: 'demo-class'
                    , area: ['900px', '460px']
                    , content: "/AdPlanLog/Index?businessPlanId=" + data.BusinessPlanID + "&adPlanId=" + data.NewAdPlanID + "&isAmdin=0"
                });
            } else if (obj.event === 'report') {
                //报表
                window.location.href = "/PlanReport/Index?NewAdPlanId=" + data.NewAdPlanID + "&IsAdmin=0";
            } else if (obj.event == "start") {
                if (data.Status == "2") {
                    layer.msg('不支持开启广告计划，已是投放状态');
                    return;
                }
                var indexload = layer.load();
                //开启操作
                $.ajax({
                    url: '/CreativePlan/UpdateAdvertPlanStatus',
                    type: 'POST',
                    data: { planId: data.ADPlanID, operationType: 1, draft_id: data.DraftId, newPlanId: data.NewAdPlanID, id: data.Id },
                    dataType: 'JSON',
                    success: function (data) {
                        layer.close(indexload);
                        if (data.result) {
                            layer.alert(data.msg);
                            window.reload();
                        } else {
                            layer.alert(data.msg);
                        }
                    }, error: function () {
                        layer.close(indexload);
                        layer.msg('提交异常');
                    }
                });
            } else if (obj.event == "end") {
                if (data.Status == "7") {
                    layer.msg('不支持暂停广告计划，已是暂停状态');
                    return;
                }
                var indexload = layer.load();
                //关闭操作
                $.ajax({
                    url: '/CreativePlan/UpdateAdvertPlanStatus',
                    type: 'POST',
                    data: { planId: data.ADPlanID, operationType: 2, draft_id: data.DraftId, newPlanId: data.NewAdPlanID, id: data.Id },
                    dataType: 'JSON',
                    success: function (data) {
                        layer.close(indexload);
                        if (data.result) {
                            layer.alert(data.msg);
                            window.location.reload();
                        } else {
                            layer.alert(data.msg);
                        }
                    }, error: function () {
                        layer.close(indexload);
                        layer.msg('提交异常');
                    }
                });
            }
        });
    });
</script>