JMGG.ManageProject.Web/Controllers/PlanReportController.cs
using JMGG.ManageProject.Business;
using JMGG.ManageProject.Common;
using JMGG.ManageProject.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JMGG.ManageProject.Web.Controllers
{
    public class PlanReportController : BaseController
    {
        private static readonly PlanReportLogic planLogic = new PlanReportLogic();

        // GET: PlanReport
        public ActionResult Index()
        {
            var NewAdPlanId = string.IsNullOrEmpty(Request["NewAdPlanId"]) ? "" : Request["NewAdPlanId"];
            var IsAdmin = string.IsNullOrEmpty(Request["IsAdmin"]) ? "" : Request["IsAdmin"];
            ViewBag.NewAdPlanId = NewAdPlanId;
            ViewBag.IsAdmin = IsAdmin == "1";

            ViewBag.UserLoginName = base.UserInfo.CompanyName + "[ID:" + base.UserInfo.BusinessID + "]";
            return View("~/Views/PlanReport/Report.cshtml");
        }

        /// <summary>
        /// 报表
        /// </summary>
        /// <returns></returns>
        public JsonResult GetAdPlanReportList()
        {
            try
            {
                int page = !string.IsNullOrEmpty(Request["page"]) ? Convert.ToInt32(Request["page"]) : 1;
                int limit = !string.IsNullOrEmpty(Request["limit"]) ? Convert.ToInt32(Request["limit"]) : 10;

                var ADName = Request["AdName"] ?? "";
                var IsAdmin = Request["IsAmdin"] ?? "";
                var startLaunchTime = Request["StartLaunchTime"] ?? "";
                var endLaunchTime = Request["EndLaunchTime"] ?? "";
                var Status = Request["LaunchStatus"] ?? "";
                var ADPlanID = Request["ADPlanID"] ?? "";
                var NewAdPlanID = Request["NewAdPlanID"] ?? "";
                #region 时间验证
                if (startLaunchTime == "" || endLaunchTime == "")
                {
                    return Json(new PlanReportPageResponse() { code = -1, msg = "请选择开始和结束时间" });
                }
                if (DateTime.Compare(DateTime.Now.AddDays(-31), Convert.ToDateTime(startLaunchTime)) > 0)
                {
                    return Json(new PlanReportPageResponse() { code = -1, msg = "时间范围不能超出当前日期30天" });
                }
                TimeSpan ts1 = new TimeSpan(Convert.ToDateTime(startLaunchTime).Ticks);
                TimeSpan ts2 = new TimeSpan(Convert.ToDateTime(endLaunchTime).Ticks);
                TimeSpan ts = ts1.Subtract(ts2).Duration();
                if (ts.Days > 30)
                {
                    return Json(new PlanReportPageResponse() { code = -1, msg = "时间范围不能超出30天" });
                }
                #endregion
                var paramRequest = new PlanReportRequest
                {
                    PageIndex = page,
                    PageSize = limit,
                    UserManageId = base.UserInfo.UserManageID,
                    AdName = ADName,
                    NewAdPlanId = NewAdPlanID,
                    StartTime = startLaunchTime,
                    EndTime = endLaunchTime,
                    LaunchStatus = Status,
                    IsAmdin = IsAdmin == "1"
                };
                if (paramRequest.PageIndex == 0)
                    paramRequest.PageIndex = 1;
                else
                    paramRequest.PageIndex = (paramRequest.PageIndex / 10) + 1;

                var result = planLogic.QueryPlanRepostListPage(paramRequest);
                if (result != null && result.count > 0)
                {
                    result.msg = "SUCCESS";
                    result.code = 0;
                }
                else
                {
                    result.msg = "未查询到数据";
                    result.code = -1;
                }
                return Json(result);
            }
            catch (Exception ex)
            {
                LogWriter.error($"GetAdPlanReportList=>获取广告信息异常：{ex.ToString() + ex.Message}");
                return Json(new PlanReportPageResponse() { code = -1, msg = "未查询到数据" });
            }
        }

        /// <summary>
        /// Excel表格导出
        /// </summary>
        /// <returns></returns>
        public JsonResult GetExcelExport()
        {
            try
            {
                var ADName = Request["AdName"] ?? "";
                var IsAdmin = Request["IsAmdin"] ?? "";
                var startLaunchTime = Request["StartLaunchTime"] ?? "";
                var endLaunchTime = Request["EndLaunchTime"] ?? "";
                var Status = Request["LaunchStatus"] ?? "";
                var ADPlanID = Request["ADPlanID"] ?? "";
                var NewAdPlanID = Request["NewAdPlanID"] ?? "";
                #region 时间验证
                if (startLaunchTime == "" || endLaunchTime == "")
                {
                    return Json(new BaseResponse() { result = false, msg = "请选择开始和结束时间" });
                }
                if (DateTime.Compare(DateTime.Now.AddDays(-31), Convert.ToDateTime(startLaunchTime)) > 0)
                {
                    return Json(new BaseResponse() { result = false, msg = "时间范围不能超出当前日期30天" });
                }
                TimeSpan ts1 = new TimeSpan(Convert.ToDateTime(startLaunchTime).Ticks);
                TimeSpan ts2 = new TimeSpan(Convert.ToDateTime(endLaunchTime).Ticks);
                TimeSpan ts = ts1.Subtract(ts2).Duration();
                if (ts.Days > 30)
                {
                    return Json(new BaseResponse() { result = false, msg = "时间范围不能超出30天" });
                }
                #endregion
                var paramRequest = new PlanReportRequest
                {
                    UserManageId = base.UserInfo.UserManageID,
                    AdName = ADName,
                    NewAdPlanId = NewAdPlanID,
                    StartTime = startLaunchTime,
                    EndTime = endLaunchTime,
                    LaunchStatus = Status,
                    IsAmdin = IsAdmin == "1"
                };
                var res = planLogic.ExportReportPlanReport(paramRequest);
                return Json(new BaseResponse { result = res.Item1, msg = res.Item2, fileUrl = res.Item3 });
            }
            catch (Exception ex)
            {
                LogWriter.error($"下载excel异常，{ex.ToString() + ex.StackTrace}");
                return Json(new BaseResponse { result = false, msg = "下载异常，请联系管理员处理" });
            }
        }
    }
}

JMGG.ManageProject.Web/Views/PlanReport/Report.cshtml
@{
    ViewBag.Title = "报表";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var NewAdPlanId = ViewBag.NewAdPlanId;
    var IsAmdin = ViewBag.IsAdmin ? "1" : "0";
}

<blockquote class="layui-elem-quote blog-manage-breadcrumb" style="margin-top: 5px;">
    <span class="layui-breadcrumb">
        <a>报表</a>
        <a href="@Url.Action("Index", "PlanReport")"><cite>活动报表中心</cite></a>
    </span>
</blockquote>

<style type="text/css">
    .layui-table-cell {
        font-size: 14px;
        padding: 0 5px;
        height: auto;
        overflow: visible;
        text-overflow: inherit;
        white-space: normal;
        word-break: break-all;
    }
</style>

<div class="layui-fluid" style="margin-top: 20px;">
    <div class="layui-card">
        <div class="layui-form ">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">广告计划名称</label>
                    <div class="layui-input-inline">
                        <input type="text" name="AdName" id="AdName" class="layui-input" value="">
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">广告计划ID</label>
                    <div class="layui-input-inline" style="width: 300px; margin-right: 57px;">
                        <input type="text" name="NewAdPlanID" id="NewAdPlanID" class="layui-input" value="@NewAdPlanId">
                    </div>
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">投放状态</label>
                    <div class="layui-input-inline">
                        <select name="LaunchStatus" id="LaunchStatus">
                            <option value="">全部状态</option>
                            <option value="1">已发布(待投放和投放中)</option>
                            <option value="2">已结束</option>
                            <option value="3">已暂停</option>
                        </select>
                    </div>
                </div>
                <div class="layui-inline">
                    <label class="layui-form-label" style="width: 100px;">选择统计时间</label>
                    <div id="put_start_time_box" class="layui-input-inline" style="width: 150px;">
                        <input type="text" class="layui-input datetime" id="StartLaunchTime" name="StartLaunchTime"
                               placeholder="投放开始时间" readonly value="">
                    </div>
                    <div style="display: inline-block; float: left; margin-right: 10px;">
                        ~
                    </div>
                    <div id="put_end_time_box" class="layui-input-inline" style="width: 150px; margin-right: 30px;">
                        <input type="text" class="layui-input datetime" id="EndLaunchTime" name="EndLaunchTime"
                               placeholder="投放结束时间" readonly value="">
                    </div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="LAY-user-front-search" lay-verify="search">
                        <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        <lable i18n="footer.search">搜索</lable>
                    </button>

                    <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="downLoad">
                        <i class="layui-icon layui-icon-download-circle layuiadmin-button-btn"></i>
                        <lable i18n="footer.search">下载数据</lable>
                    </button>
                </div>

            </div>
        </div>
    </div>

    <div class="layui-card-body">
        <table id="LAY-CreativePlan" lay-filter="LAY-CreativePlan"></table>
    </div>
</div>

@section Scripts{
    <script>
        var IsAmdin=@IsAmdin;
        layui.use(['laydate','form', 'table', 'layer'], function () {
            var $ = layui.jquery;
            var table = layui.table;
            var layer = layui.layer;
            var laydate = layui.laydate;
            var form = layui.form;

            //日期范围选择
            laydate.render({
                elem: '#StartLaunchTime',
                value: GetDay(30)
            });
            laydate.render({
                elem: '#EndLaunchTime',
                value: GetDay(0)
            });

            function GetDay(n) {
                var n = n;
                var d = new Date();
                var year = d.getFullYear();
                var mon = d.getMonth() + 1;
                var day = d.getDate();
                if (day <= n) {
                    if (mon > 1) {
                        mon = mon - 1;
                    }
                    else {
                        year = year - 1;
                        mon = 12;
                    }
                }
                d.setDate(d.getDate() - n);
                year = d.getFullYear();
                mon = d.getMonth() + 1;
                day = d.getDate();
                s = year + "-" + (mon < 10 ? ('0' + mon) : mon) + "-" + (day < 10 ? ('0' + day) : day);
                return s;
            }

            table.set({
                parseData: function (res) {
                    return {
                        code: res.status, //解析接口状态
                        msg: res.msg, //解析提示文本
                        count: res.data.total ? res.data.total.total : 0, //解析数据长度
                        data: res.data, //解析数据列表
                    }
                },
            })

            //表格加载
            var cols = [[
                { field: 'NewAdPlanId', title: '广告ID', }
                , { field: 'LaunchDateStr', title: '投放时间', }
                , { field: 'AdName', title: '广告名称', }
                , {
                    field: 'LaunchStatus', title: '投放状态', templet: function (d) {
                        if (d.LaunchStatus == 1) { return '已发布' } if (d.LaunchStatus == 2) { return '已结束' } if (d.LaunchStatus == 3) { return '已暂停' }
                    }
                }
                , { field: 'PV', title: '爆光(PV)', }
                , { field: 'CPV', title: '点击(CPV)', }
                , { field: 'CTRPV', title: 'CTR(PV)', }
                , { field: 'UV', title: '爆光(UV)', }
                , { field: 'CUV', title: '点击(CUV)', }
                , { field: 'CTRUV', title: 'CTR(UV)', }
                , { field: 'DPV', title: '下载量(DPV)', }
                , { field: 'InstallCount', title: '安装量', }
                , { field: 'ActualAmount', title: '实际消耗金额', }
            ]]
            var tableIns = table.render({
                elem: '#LAY-CreativePlan',
                url: '/PlanReport/GetAdPlanReportList', //数据接口
                cols: cols,
                method: 'post',
                done: function (res) { },
                parseData: function (res) {
                    return {
                        code: res.code, //解析接口状态
                        msg: res.msg, //解析提示文本
                        count: res.count ? res.count : 0, //解析数据长度
                        data: res.data, //解析数据列表
                    }
                },
                page: true,
                text: {
                    none: '暂无相关数据',
                },
                where: {
                    AdName: $.trim($("#AdName").val()),
                    StartLaunchTime: $.trim($("#StartLaunchTime").val()),
                    EndLaunchTime: $.trim($("#EndLaunchTime").val()),
                    Status: $.trim($("#Status").val()),
                    ADPlanID: $.trim($("#ADPlanID").val()),
                    NewAdPlanID: $.trim($("#NewAdPlanID").val()),
                    IsAmdin: IsAmdin,
                    LaunchStatus: $("#LaunchStatus").val()
                },
                defaultToolbar: [],
            })
            //搜索事件
            form.on('submit(LAY-user-front-search)', function (data) {
                var field = data.field
                //执行重载
                tableIns.reload({
                    page: {
                        curr: 1,
                    },
                    where: {
                        AdName: $.trim($("#AdName").val()),
                        StartLaunchTime: $.trim($("#StartLaunchTime").val()),
                        EndLaunchTime: $.trim($("#EndLaunchTime").val()),
                        Status: $.trim($("#Status").val()),
                        ADPlanID: $.trim($("#ADPlanID").val()),
                        NewAdPlanID: $.trim($("#NewAdPlanID").val()),
                        IsAmdin: IsAmdin,
                        LaunchStatus: $("#LaunchStatus").val()
                    },
                })
            })

            //下载事件
            form.on('submit(downLoad)', function (data) {
                var loadIndex = layer.load();
                $.post("/PlanReport/GetExcelExport", { AdName: $.trim($("#AdName").val()), StartLaunchTime: $.trim($("#StartLaunchTime").val()), EndLaunchTime: $.trim($("#EndLaunchTime").val()), Status: $.trim($("#Status").val()), ADPlanID: $.trim($("#ADPlanID").val()), NewAdPlanID: $.trim($("#NewAdPlanID").val()), IsAmdin: IsAmdin, LaunchStatus: $("#LaunchStatus").val() }, function (data) {
                    layer.close(loadIndex);
                    if (data != null && data.result) {
                        layer.alert(data.msg);
                        window.open(data.fileUrl);
                    } else {
                        layer.alert(data.msg);
                    }  
                }).error(function () { layer.close(loadIndex); });
            })
        });
    </script>

}