JMGG.ManageProject.Web/Controllers/BasicInfoController.cs
using JMGG.ManageProject.Business;
using JMGG.ManageProject.Common;
using JMGG.ManageProject.Model.Creative;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JMGG.ManageProject.Model.User;
using Newtonsoft.Json;

namespace JMGG.ManageProject.Web.Controllers
{
    public class BasicInfoController : BaseController
    {
        private static readonly UserLogic userLogic = new UserLogic();

        // GET: CreativePlan
        public ActionResult From()
        {
            ViewBag.IsAdmin = false;
            ViewBag.UserLoginName = base.UserInfo.CompanyName + "[ID:" + base.UserInfo.BusinessID + "]";
            var userInfo = userLogic.QueryUserInfoByBusinessID(new UserInfo
            {
                UserManageId = base.UserInfo.UserManageID,
            });
            if (userInfo != null && !string.IsNullOrEmpty(userInfo.BizInfoJson))
            {
                var bizInfoObj = JsonConvert.DeserializeObject<BizInfoEntity>(userInfo.BizInfoJson);
                userInfo.BizInfo = bizInfoObj;
            }
            return View("~/Views/BasicInfo/From.cshtml", userInfo);
        }
    }
}

JMGG.ManageProject.Web/Views/BasicInfo/From.cshtml
@using JMGG.ManageProject.Model.User
@model UserInfo
@{
    ViewBag.Title = "基本信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<blockquote class="layui-elem-quote blog-manage-breadcrumb" style="margin-top: 5px;">
    <span class="layui-breadcrumb">
        <a>系统</a>
        <a href="@Url.Action("From", "BasicInfo")"><cite>基本信息</cite></a>
    </span>
</blockquote>

<div class="layui-fluid layui-form" id="form" style="margin-top: 30px;">
    <div class="site-title">
        <fieldset class="layui-elem-field layui-field-title">
            <legend>基本信息</legend>
        </fieldset>
        <div class="layui-row">
            <form class="layui-form">
                <div class="layui-form-item">
                    <label class="layui-form-label">商家ID</label>
                    <div class="layui-input-block">
                        <input type="text" name="BussinessID" required disabled lay-verify="required" value="@Model.BussinessID"
                               autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">代理商ID</label>
                    <div class="layui-input-block">
                        <input type="text" name="AgentId" disabled value="@Model.AgentId" autocomplete="off"
                               class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">公司名称</label>
                    <div class="layui-input-block">
                        <input type="text" name="CompanyName" disabled value="@Model.CompanyName" autocomplete="off"
                               class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">通讯地址</label>
                    <div class="layui-input-block">
                        <input type="text" name="Address" disabled value="@Model.Address"
                               autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">网站链接</label>
                    <div class="layui-input-block">
                        <input type="text" name="URL" disabled value="@Model.WebSite" autocomplete="off"
                               class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">产品名称</label>
                    <div class="layui-input-block">
                        <input type="text" name="ProductId" disabled value="@Model.ProductId" autocomplete="off"
                               class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">联系人姓名</label>
                    <div class="layui-input-block">
                        <input type="text" name="Contacts" value="@Model.Contacts" autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">手机号</label>
                        <div class="layui-input-inline">
                            <input type="text" name="Mobile" value="@Model.Mobile" data-value=""
                                   autocomplete="off" class="layui-input">
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">邮箱</label>
                        <div class="layui-input-inline">
                            <input type="text" name="Email" required value="@Model.Email"
                                   data-value="" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="site-title">
        <fieldset class="layui-elem-field layui-field-title">
            <legend><a name="use">资质信息</a></legend>
        </fieldset>
        <div class="layui-row" style="padding-left: 50px;padding-top: 10px;">
            <div class="layui-tab">
                <ul class="layui-tab-title">
                    <li class="layui-this">营业执照</li>
                    <li>ICP资质备案</li>
                </ul>
                <div class="layui-tab-content" style="padding-left: 0px;">
                    <div class="layui-tab-item">
                        <div class="layui-col-md6">
                            <table class="layui-table" lay-size="lg">
                                <colgroup>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th>营业执照</th>
                                        <th>营业执照统一社会信用代码</th>
                                        <th>资质到期日期</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.BizInfo != null && Model.BizInfo.LicenseInfoList != null && Model.BizInfo.LicenseInfoList.Count > 0)
                                    {
                                        for (int i = 0; i < Model.BizInfo.LicenseInfoList.Count; i++)
                                        {
                                            <tr>
                                                <td>
                                                    <a name='BusinessHeat' href="@Model.BizInfo.LicenseInfoList[i].BizPicUrl" target="_blank">
                                                        <img src="@Model.BizInfo.LicenseInfoList[i].BizPicUrl" alt="">
                                                    </a>
                                                </td>
                                                <td>@Model.BizInfo.LicenseInfoList[i].CreditCode</td>
                                                <td>@Model.BizInfo.LicenseInfoList[i].ExpirationDate</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="layui-tab-item layui-show">
                        <div class="layui-col-md6">
                            <table class="layui-table" lay-size="lg">
                                <colgroup>
                                    <col width="150">
                                    <col width="200">
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th>营业执照</th>
                                        <th>资质到期日期</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.BizInfo != null && Model.BizInfo.IcpInfoList != null && Model.BizInfo.IcpInfoList.Count > 0)
                                    {
                                        for (int i = 0; i < Model.BizInfo.IcpInfoList.Count; i++)
                                        {
                                            <tr>
                                                <td>
                                                    <a name='QualificationUrl' href="@Model.BizInfo.IcpInfoList[i].BizPicUrl" target="_blank">
                                                        <img src="@Model.BizInfo.IcpInfoList[i].BizPicUrl" alt="">
                                                    </a>
                                                </td>
                                                <td>@Model.BizInfo.IcpInfoList[i].ExpirationDate</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

JMGG.ManageProject.Web/Views/BasicInfo/Index.cshtml
@{
    ViewBag.Title = "基本信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@{
    ViewBag.Title = "基本信息";
}
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>基本信息</title>
</head>

<body>
    <div class="layui-fluid" style="margin-top: 30px;">
        <div class="layui-card">
            <div class="layui-form ">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label" i18n="footer.user name">名称</label>
                        <div class="layui-input-block">
                            <input type="text" name="uName" placeholder="请输入" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                </div>
                <div style="padding-bottom: 10px;">
                    <button class="layui-btn layuiadmin-btn-useradmin" lay-submit lay-filter="LAY-user-front-search">
                        <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        <lable i18n="footer.search">搜索</lable>
                    </button>
                </div>
            </div>

            <div class="layui-card-body">
                <table id="LAY-BasicInfo" lay-filter="LAY-BasicInfo"></table>
                <script type="text/html" id="barDemo">
                    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
                    <a class="layui-btn layui-btn-xs" lay-event="edit">查看报表</a>
                    <a class="layui-btn layui-btn-xs" lay-event="edit">查看报表</a>
                    <a class="layui-btn layui-btn-xs" lay-event="edit">操作记录</a>
                </script>
            </div>
        </div>
    </div>
</body>

</html>
<script>
    layui.use(['form', 'jquery', 'table', 'layer'], function () {
        var $ = layui.jquery;
        var form = layui.form;
        var table = layui.table;
        var layer = layui.layer;


        table.set({
            parseData: function (res) {
                return {
                    code: res.status, //解析接口状态
                    msg: res.msg, //解析提示文本
                    count: res.data.total ? res.data.total.total : 0, //解析数据长度
                    data: res.data, //解析数据列表
                }
            },
        })
        //表格加载
        var cols = [[
            { field: 'BussinessID', title: '开关', }
            , { field: 'UserName', title: '广告计划ID', }
            , { field: 'CompanyName', title: '商家计划ID', }
            , { field: 'CreateTimeStr', title: '名称', }
            , { field: 'CreateTimeStr', title: '投放点位', }
            , { field: 'CreateTimeStr', title: '计费方式', }
            , { field: 'CreateTimeStr', title: '单价', }
            , { field: 'CreateTimeStr', title: '单日预算', }
            , { field: 'CreateTimeStr', title: 'CTR', }
            , { field: 'CreateTimeStr', title: 'ECPM(CPC)', }
            , { field: 'CreateTimeStr', title: '投放排期', }
            , { field: 'CreateTimeStr', title: '投放时段', }
            , { field: 'CreateTimeStr', title: '状态', }
            , { field: 'CreateTimeStr', title: '审核原因', }
            , { fixed: 'right', title: '操作', toolbar: '#barDemo', width: 300 }
        ]]
        var tableIns = table.render({
            elem: '#LAY-BasicInfo',
            url: '/BasicInfo/GetList', //数据接口
            cols: cols,
            method: 'post',
            done: function (res) { },
            parseData: function (res) {
                debugger;
                return {
                    code: res.code, //解析接口状态
                    msg: res.msg, //解析提示文本
                    count: res.count ? res.count : 0, //解析数据长度
                    data: res.data, //解析数据列表
                }
            },
            page: true,
            text: {
                none: '暂无相关数据',
            },
            defaultToolbar: [],
        })
        //搜索事件
        form.on('submit(LAY-user-front-search)', function (data) {
            var field = data.field
            //执行重载
            tableIns.reload({
                page: {
                    curr: 1,
                },
                where: field,
            })
        })

    });
</script>